name: Bare Minimum Requirements

on: [push, pull_request]

jobs:
  job1:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Bare Minimum Requirements
          uses: actions/setup-node@v1
          with:
            node-version: "16"
        - run: npm install
        - run: npm test
  job2:
    needs: job1
     test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Bare Minimum Requirements
          uses: actions/setup-node@v1
          with:
            node-version: "16"
        - run: npm install
        - run: npm test
